apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-k8s-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aws-k8s-app
  template:
    metadata:
      labels:
        app: aws-k8s-app
    spec:

      imagePullSecrets:
        - name: ecr-secret

      containers:
        - name: aws-k8s-app
          image: 679346886253.dkr.ecr.us-east-1.amazonaws.com/aws-k8s-app:2b9177480d288db77d7ff8508f1aa66bfc55102f
          ports:
            - containerPort: 8000
          env:
            - name: APP_VERSION
              value: "v1"