[k8s_master]
98.92.152.204 ansible_user=admin ansible_ssh_private_key_file=~/.ssh/id_rsa private_ip=10.0.1.128

[k8s_worker]
35.171.146.63 ansible_user=admin ansible_ssh_private_key_file=~/.ssh/id_rsa
