[k8s_master]
<MASTER_01_IP> ansible_user=admin ansible_ssh_private_key_file=~/.ssh/id_rsa private_ip=<MASTER_01_PRIVATE_IP>

[k8s_worker]
<WORKER_01_IP> ansible_user=admin ansible_ssh_private_key_file=~/.ssh/id_rsa
