[k8s_master]
3.215.190.63 ansible_user=admin ansible_ssh_private_key_file=~/.ssh/id_rsa private_ip=10.0.1.139

[k8s_worker]
98.92.156.25 ansible_user=admin ansible_ssh_private_key_file=~/.ssh/id_rsa
